### ISSUE TITLE
RFE: Configure 'touch' style tokens to started on app open.

### ISSUE THREAD

**Issue by wmealing** [fidesmo/free-otp#17]
When the app is brought into the foreground ( either through starting or switching to the app ) could we have it automatically show the value instead of having to hit the blue square ?

I -might- be able to do this, but since its your code I figured you'd know best.

Thanks.

**Comment by petter-fidesmo** [comment]
Hi @wmealing 

This is our own fork of this application that supports the use of NFC security tokens (like our [Fidesmo Card](http://shop.fidesmo.com/)). The original project are tracking their issues here: https://fedorahosted.org/freeotp/report

**Comment by wmealing** [comment]
Oh sorry about that, i saw the logo, the name.. I thought it was the upstream (since i didnt see forked from) you can close this up.

**Comment by petter-fidesmo** [comment]
No worries!
